### ISSUE TITLE
User can view all movies at hopflix.com/movies

### ISSUE THREAD

**Issue by kagresta** [hop-shop/hop-shop#1]
Subtasks:
- [x] Set up database models for Users, Movies, Purchased/Cart #2 
- [x] Create dummy data and seed database #3 
- [x] Ensure database is populating correctly #4
- [x] Create express route to find all movies (i.e. hopflix/api/movies) #5
- [x] Create movies component #6
- [x] Create movies redux reducer #7
