### ISSUE TITLE
User should be able to view home page as a guest or as a loggedIn user

### ISSUE THREAD

**Issue by kagresta** [hop-shop/hop-shop#8]
Subtasks:
- [x] Create homepage component - logged in #9
- [ ] Create homepage component - guest #10
- [ ] Create homepage redux reducer #11
